### ISSUE TITLE
industry demand expansion

### ISSUE THREAD

**Issue by hazemakhalek** [pypsa-meets-earth/pypsa-earth-sec#126]
- [x] Restructure the the industrial demand sector to make it more comprehensible and well adapted to PyPSA-Earth data sources.

- [x] The industry demand data creation now relies on emission data to generate the distribution key of the facilities. A required addition would be in `build_indutrial_distribution_key.py` in function `build_nodal_distribution_key` by adapting the function to use production quantities when available.
Check the #TODO in the script on branch validate_demand

- [ ] #127

**Comment by energyLS** [comment]
Done in #238
