### ISSUE TITLE
Add option to scale up certain industries in the future

### ISSUE THREAD

**Issue by hazemakhalek** [pypsa-meets-earth/pypsa-earth-sec#127]
Currently, the production of the future is only a matter of changing the production technology. While this might be okay for Europe, it is definitely not the case in developing countries that are aiming to increase their current industrial capacities. (e.g. Morocco for Ammonia)

Possible function to add the feature is `industry_prod_tomorrow` in script `build industrial_production_tomorrow.py`

**Comment by energyLS** [comment]
Done in #238
