### ISSUE TITLE
Include a global dataset for airports and ports

### ISSUE THREAD

**Issue by hazemakhalek** [pypsa-meets-earth/pypsa-earth-sec#185]
## A global dataset for airports and ports is needed

In order to disaggregate the aviation and navigation demand to the right nodes, the model needs a distribution key to map the national level demand. The dataset should ideally come from open data source and include the following columns: `country`, `longitude`, `latitude`, `fraction`, `source`, and `dissaregation metric`
Automating the data acquisition and processing would be a nice feature, including the cleaned files in the repo could also work if the license allows it

- [ ] airports dataset
- [ ] ports dataset

**Comment by pz-max** [comment]
Hey @Eddy-JV, all data exist on OPENSTREETMAP. Lets extract that with https://github.com/pypsa-meets-earth/earth-osm We just need to builld that interface. Maybe @mnm-matin can give you some hints how to do it.
