### ISSUE TITLE
Misintegration of Biomass potentials

### ISSUE THREAD

**Issue by hazemakhalek** [pypsa-meets-earth/pypsa-earth-sec#232]
## Describe the Bug
Currently, the (dummy) values of the biomass potentials is set to every node in the system leading to a large overestimation.

https://github.com/pypsa-meets-earth/pypsa-earth-sec/blob/99ac2ea08423a737c7a7feea69dda5dbae3e6b31/scripts/prepare_sector_network.py#L504-L523

**Comment by energyLS** [comment]
Global biomass dataset (but I think not energy-related): https://globbiomass.org/wp-content/uploads/GB_Maps/Globbiomass_global_dataset.html

**Comment by energyLS** [comment]
Further point of discussion: Spatially resolved biomass/biogas potentials?
