### ISSUE TITLE
Issue with build_cutout

### ISSUE THREAD

**Issue by doneachh** [pypsa-meets-earth/pypsa-earth-sec#278]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-africa/pypsa-earth-sec/tree/main) branch or the latest [release](https://github.com/pypsa-meets-africa/pypsa-earth-sec/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-africa` environment](https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

As soon as i am running the model a second (or more) time, there is a error message basically saying "cutout already exists. Delete it or set build_cutout = false". As soon as i set build_cutout = false, i receive an error message basically saying build_cutout has to be true or something like that.
--> workaround right now is to comment out "terminate_if_cutout_exists" in the snakefile to run the model and set build_cutout=true. 

## Error Message

Exception with build_cutout enabled:

```bash
Exception in file /mnt/c/Users/aca39878/Documents/Git/Africa/pypsa-earth-sec/pypsa-earth/Snakefile, line 336:
An option `build_cutout` is enabled, while a cutout file 'cutouts/cutout-2013-era5.nc' still exists and risks to be overwritten. If this is an intended behavior, please move or delete this file and re-run the rule. Otherwise, just disable the `build_cutout` rule in the config file.
  File "/mnt/c/Users/aca39878/Documents/Git/Africa/pypsa-earth-sec/pypsa-earth/Snakefile", line 344, in <module>
  File "/mnt/c/Users/aca39878/Documents/Git/Africa/pypsa-earth-sec/pypsa-earth/Snakefile", line 336, in terminate_if_cutout_exists
ERROR:snakemake.logging:Exception in file /mnt/c/Users/aca39878/Documents/Git/Africa/pypsa-earth-sec/pypsa-earth/Snakefile, line 336:
An option `build_cutout` is enabled, while a cutout file 'cutouts/cutout-2013-era5.nc' still exists and risks to be overwritten. If this is an intended behavior, please move or delete this file and re-run the rule. Otherwise, just disable the `build_cutout` rule in the config file.
  File "/mnt/c/Users/aca39878/Documents/Git/Africa/pypsa-earth-sec/pypsa-earth/Snakefile", line 344, in <module>
  File "/mnt/c/Users/aca39878/Documents/Git/Africa/pypsa-earth-sec/pypsa-earth/Snakefile", line 336, in terminate_if_cutout_exists
```

Exception with build_cutout = false:

```bash
MissingRuleException:
No rule to produce cutouts/cutout-2013-era5.nc (if you use input functions make sure that they don't raise unexpected exceptions).
ERROR:snakemake.logging:MissingRuleException:
No rule to produce cutouts/cutout-2013-era5.nc (if you use input functions make sure that they don't raise unexpected exceptions).
```

**Comment by doneachh** [comment]
Hi @davide-f ! 
Here the error messages, we've spoke about in the pypsa-earth sec meeting. :)

**Comment by davide-f** [comment]
With the fix we discussed during the meeting this issue should be bypassed.
You find it in the shared branch

**Comment by doneachh** [comment]
@davide-f Great! :) Guess we can close this issue then?

**Comment by davide-f** [comment]
Agree :) closing
