### ISSUE TITLE
Add_heat issue: None in [list of  snapshots] not found in [index]

### ISSUE THREAD

**Issue by davide-f** [pypsa-meets-earth/pypsa-earth-sec#94]
In order to finalize the merging of all branches, in the pypsa-africa-integration pr #68 , the add_heat function lead to an error at https://github.com/pypsa-meets-africa/pypsa-earth-sec/blob/d3406bd35bf99ed91a10c8c0f9a4f75a4413a7bd/scripts/prepare_sector_network.py#L1231-L1238

**Comment by energyLS** [comment]
Outdated, should be resolved by now.
