### ISSUE TITLE
Enable non-null land transport electric share

### ISSUE THREAD

**Issue by davide-f** [pypsa-meets-earth/pypsa-earth-sec#95]
In the test case for Nigeria, the workflow fails when land_transport_electric_share is non-null (even 0.0001 makes it fail) at
https://github.com/pypsa-meets-africa/pypsa-earth-sec/blob/d3406bd35bf99ed91a10c8c0f9a4f75a4413a7bd/config.yaml#L115

This shall be addressed to avoid this issue. The feeling is that in Nigeria some buses may not have capacity to meet a non-zero land_transport_electric_share, yet it shall be investigated

**Comment by energyLS** [comment]
I will look into this. It seems like it works for Morocco (https://github.com/pypsa-meets-africa/pypsa-earth-sec/commit/b1c9706dc800defed64b8ad521c16eb5be82d4ab#diff-d8d0422389f03d783e32e627250fe29834bd09c6361640d1ff00661dd6820034R123), but not for Nigeria as reported

**Comment by energyLS** [comment]
@cschau-ieg tested this, and did not encounter this problem again.
